version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: silva
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
 
